version: "3.9"

services:
  magneto-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Bind mount local backend → /app/backend
      - ./backend:/app/backend
      # Bind mount local frontend → /app/frontend
      - ./frontend:/app/frontend
    # Override the default CMD to run your dev server(s)
    working_dir: /app/backend
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      # If you need the Python path for your Node-based spawn commands
      PYTHONPATH: /app/magneto
    # If you have more environment variables or a database, add them here